# Generated by Django 5.2.8 on 2026-02-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=255)),
                ('description2', models.CharField(blank=True, max_length=255)),
                ('description3', models.CharField(blank=True, max_length=255)),
                ('description4', models.CharField(blank=True, max_length=255)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (GNF)')),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forfaits/')),
                ('type', models.CharField(choices=[('FO', 'Fibre Optique'), ('FH', 'Faisceau Hertzien')], default='FO', max_length=10)),
                ('is_bon_plan', models.BooleanField(default=False)),
                ('bg_color', models.CharField(blank=True, choices=[('#2596be', 'Bleu Sky (#2596be)'), ('#cf0606', 'Rouge CF (#cf0606)')], help_text="Couleur d'arrière-plan (sélection : --bleu-sky ou --rouge-cf)", max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/')),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('is_bon_plan', models.BooleanField(default=False)),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('caracteristiques', models.TextField(blank=True, help_text='Caractéristiques techniques ou points forts du produit')),
                ('reference', models.CharField(blank=True, help_text='Référence ou SKU du produit', max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='quickblocks/')),
                ('url_name', models.CharField(help_text="Nom de l'URL Django (ex: 'forfaits', 'faq')", max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('extra_description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Classe Bootstrap Icons (ex: 'bi-box-seam')", max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WifiTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 1 heure, 2 heures, 1 jour', max_length=100)),
                ('duree_heures', models.PositiveIntegerField(help_text='Durée en heures')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en GNF', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Type de ticket WiFi',
                'verbose_name_plural': 'Types de tickets WiFi',
                'ordering': ['ordre', 'duree_heures'],
            },
        ),
        migrations.CreateModel(
            name='ZoneCouverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActualiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.actualite')),
            ],
        ),
        migrations.CreateModel(
            name='FaqImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faq/')),
                ('legend', models.CharField(blank=True, max_length=255)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.faq')),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.faqsection'),
        ),
        migrations.CreateModel(
            name='FaqStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.faq')),
            ],
        ),
        migrations.CreateModel(
            name='FaqStepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faq_steps/')),
                ('legend', models.CharField(blank=True, max_length=255)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.faqstep')),
            ],
        ),
        migrations.CreateModel(
            name='ForfaitDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(help_text='Texte de description (affiché dans la carte)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (plus petit = en haut)")),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.forfait')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_reception', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('preparation', 'En préparation'), ('recuperee', 'Récupérée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agence')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to=settings.AUTH_USER_MODEL)),
                ('commercial', models.ForeignKey(blank=True, help_text='Commercial en charge de cette commande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_assigned', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.commune')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_debited', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='core.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='core.souscategorie'),
        ),
        migrations.CreateModel(
            name='WifiTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='Identifiant de connexion', max_length=20, unique=True)),
                ('mot_de_passe', models.CharField(help_text='Mot de passe de connexion', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('hotspot', models.CharField(blank=True, help_text='Nom du hotspot utilisé', max_length=100)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wifitickettype')),
            ],
            options={
                'verbose_name': 'Ticket WiFi',
                'verbose_name_plural': 'Tickets WiFi',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeSouscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RDV_CONFIRME', 'Rendez‑vous confirmé'), ('ETUDE_SITE', 'Étude de site'), ('SURVEY', 'Survey / Relevé de site'), ('POSE_BOOM', 'Pose du boom'), ('COTATION', 'Cotation / Devis'), ('SIGNE', 'Client signé'), ('INSTALLATION', 'Installation'), ('ACTIVATION', 'Activation'), ('FACTURATION', 'Facturation'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('note_interne', models.TextField(blank=True, help_text='Note interne pour le suivi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(blank=True, help_text='Commercial en charge de la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_souscription', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commune')),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forfait')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zonecouverture')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='core.zonecouverture'),
        ),
    ]
